### ISSUE TITLE
Incorrect "misspelled link" markup

### ISSUE THREAD

**Issue by Noordfrees** [widelands/widelands-website#361] opened 2021-10-18 08:24 UTC
In this thread https://www.widelands.org/forum/topic/5242
the links to https://www.widelands.org/wiki/Download#all-distributions_1
are shown in yellow and have a tooltip "This link is misspelled or missing. Click to create it anyway."
even though the link is valid and works (points to a subsection in a wiki page).

**Comment by frankystone** [comment] 2021-12-12 17:11
The problem is a missing slash between `Download` and `#all-distributions_1`

Wrong: [[ Download#all-distributions_1| flathub-beta ]]
Correct: [[ Download/#all-distributions_1| flathub-beta ]]

When copying the link from the address-bar of the browser, or by copying it from the TOC from the wikiarticle the slash is part of the link.

You can also try it out yourself: Open the link https://www.widelands.org/wiki/Download#all-distributions_1 (without slash) and look at your browsers address-bar. The slash will be inserted (at least here on opera-browser).

Closing as won't fix.

**Closed by frankystone** 2021-12-12 17:11 UTC
Labels: bug, wontfix
