### ISSUE TITLE
Error while loading tribe 'barbarians':

### ISSUE THREAD

**Issue by jcy1001** [widelands/widelands-website#381] opened 2022-07-02 06:21 UTC
[00:06:44.773 real] ERROR: ##############################
[00:06:44.773 real] ERROR:   FATAL EXCEPTION: Error while loading tribe 'barbarians': [../src/scripting/lua_errors.cc:22] tribe barbarians: Failed adding immovable 'wheatfield_tiny': [../src/scripting/lua_errors.cc:22] wheatfield_tiny: Error in immovable program main: Error reading line 'animate=idle duration:30s': basic_string::append
[00:06:44.773 real] ERROR: stack traceback:
[00:06:44.773 real] ERROR: 	[string "tribes/immovables/wheatfield/tiny/init.lua"]:5: in main chunk
[00:06:44.773 real] ERROR: 	[C]: in method 'new_tribe'
[00:06:44.773 real] ERROR: 	[string "tribes/initialization/barbarians/units.lua"]:10: in main chunk
[00:06:44.773 real] ERROR: stack traceback:
[00:06:44.773 real] ERROR: 	[string "tr
[00:06:44.773 real] ERROR: ##############################
[00:06:44.773 real] ERROR:   Please report this problem to help us improve Widelands.
[00:06:44.773 real] ERROR:   You will find related messages in the standard output (stdout.txt on Windows).
[00:06:44.773 real] ERROR:   You are using build 1.0 (Release).
[00:06:44.773 real] ERROR:   Please add this information to your report.
[00:06:44.773 real] ERROR:   If desired, Widelands attempts to create an emergency savegame.
[00:06:44.773 real] ERROR:   It is often – though not always – possible to load it and continue playing.
[00:06:44.773 real] ERROR: ##############################

**Comment by Noordfrees** [comment] 2022-07-02 07:42
Not a website issue, duplicate of https://github.com/widelands/widelands/issues/5464

**Closed by Noordfrees** 2022-07-02 07:42 UTC
